name: SONOZ
description: Discover & Propel new DJs.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  readmore: ^1.0.0
  flutter_staggered_grid_view: ^0.3.2
  cloud_firestore: ^0.14.4
  firebase_auth: ^0.18.4+1
  firebase_core: ^0.5.3
  firebase_storage: ^5.2.0
  permission_handler: ^5.0.1+1
  image_picker: ^0.6.7+15
  path_provider: ^1.6.24
  file_picker: ^2.1.4
  url_launcher: ^5.7.10
  modal_bottom_sheet: ^1.0.0+1
  flutter_cache_manager: ^2.1.0
  audioplayers: ^0.16.2
  flutter_screen_recording: ^1.1.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/like.png
    - lib/assets/imageStudio.jpg
    - lib/assets/home.png
    - lib/assets/homeActive.png
    - lib/assets/user.png
    - lib/assets/userActive.png
    - lib/assets/logo.png
    - lib/assets/sound.png
    - lib/assets/duality.jpg
    - lib/assets/duality1.jpg
    - lib/assets/duality2.jpg
    - lib/assets/duality3.jpg
    - lib/assets/nicky.jpg
    - lib/assets/likeOff.png
    - lib/assets/pause.png
    - lib/assets/comment.png
    - lib/assets/play.png
    - lib/assets/playOff.png
    - lib/assets/instagram.png
    - lib/assets/email.png
    - lib/assets/share.png
    - lib/assets/checked.png
    - lib/assets/search.png
    - lib/assets/subscription.png
    - lib/assets/shop.png
    - lib/assets/close.png
    - lib/assets/returnButton.png
    - lib/assets/forward.png
    - lib/assets/music.mp3
    - lib/assets/spotify.png




  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
